### ISSUE TITLE
Doesn't support loading from InputStream

### ISSUE THREAD

**Issue by romanman** [maxmind/geoip-api-java#30]
Hey guys , you have a great api and 
I really like to use until I bumped to a
stage when I have to run in complete 
jar in that case load LookupService
with File doesn't work, only
InputStream will help, is it any plan to 
add that functionality ?

**Comment by oschwald** [comment]
Our GeoIP2 API [supports this](https://github.com/maxmind/GeoIP2-java/blob/master/src/main/java/com/maxmind/geoip2/DatabaseReader.java#L78). We don't have plans on adding this to the Legacy API, but we would likely accept a reasonable PR that included tests.

**Comment by romanman** [comment]
Thanks @oschwald , that looks like very good way, 
can you provide a short snippet with 2-3 lines of code
to display how the database is loaded

**Comment by oschwald** [comment]
Closing this as future development is focused on the GeoIP2 API.
