### ISSUE TITLE
In consistency in response  

### ISSUE THREAD

**Issue by meetshishir** [maxmind/geoip-api-java#31]
We have been using GEOIP_MEMORY_CACHE option for finding location based on IP .Response time in 90% of cases is fast but for some it just got stuck . On a Single thread environment the performance is consistence .Does any one also have faced similar issue ?

**Comment by oschwald** [comment]
This is the first report of such an issue. By "it just got stuck" do you mean the thread deadlocked?

**Comment by oschwald** [comment]
I am closing this based on lack of information. If you can provide more details, I will reopen.
