### ISSUE TITLE
Exception information is suppressed

### ISSUE THREAD

**Issue by mweiczorek** [maxmind/geoip-api-java#46]
I'm getting a bunch of lines printed to stderr when I run my Rest API project using your Lookup service:

`IO Exception while seting up segments`

This was printed to stderr via `System.err.println` in `com.maxmind.geoip.LookupService` in the two methods `getLocationV6` and `getLocation`. 

The problem I have is, you're catching an `IOException` and printing to standard error stream with the vague message `IO Exception while seting up segments` instead of offering useful information and a stack trace.

Since you've built a public API, it's not Java convention to swallow (ignore, suppress) these IO exceptions with no clue to for the user when something goes wrong. These methods should throw the IO exception up for the user's implementation to handle. This is the proper Java way of doing things. Unfortunately, it causes a lot of extra work for me to pin down the error rather than just referring to a stack trace.

Since this library has been published, you can't refactor and introduce breaking changes, but what you can do is to add a debug option somewhere that will allow the stack trace from that exception to be printed to stdout, so your users can determine what went wrong.

**Comment by oschwald** [comment]
Closing as this is a breaking change and this is a legacy library.
