### ISSUE TITLE
Cannot find dbfile

### ISSUE THREAD

**Issue by LiMengyang990726** [maxmind/geoip-api-java#48]
I have built successfully with 
`mvn clean install`
and 
`mvn package`

However, I am not able to see any jar file in my `target`, and thus in `LookupService cl = new LookupService(dbfile,
            LookupService.GEOIP_MEMORY_CACHE | LookupService.GEOIP_CHECK_CACHE);` the `dbfile` cannot be found.

Can someone help me with this?

**Comment by oschwald** [comment]
The database files are distributed separately. MaxMind no longer offers the legacy GeoLite databases, but it does provide paid databases in the legacy format. I would suggest using GeoIP2 for new projects: https://github.com/maxmind/GeoIP2-java
